### ISSUE TITLE
Button labels are not showing on Kubuntu linux

### ISSUE THREAD

**Issue by apahl** [oskca/webview#1]
Hi, thanks a lot for this very nice library.

It seems that for the `bindEx` example, the button labels are not shown on Kubuntu 17.10, using latest Nim devel. The buttons do work as expected, though.
![bindex](https://user-images.githubusercontent.com/9406836/34783146-0581fd48-f62b-11e7-8e0a-ae2c780ea547.png)

Do you have an idea how to fix this?

Kind regards,
Axel

**Comment by oskca** [comment]
It seems like some thing wrong happened to `webkit`

Have you tried to run the code without the `bindProcs` section?

**Comment by apahl** [comment]
That does not change the behaviour.  

To me this looks like a styling issue, as if the button labels have the same color as the buttons themselves, because when I click on a button (and keep it pressed, tricky to screenshot), I can see the label:
![bindex1](https://user-images.githubusercontent.com/9406836/34822989-18c0a942-f6c9-11e7-81a7-65238baea751.png)


I will see if I can change the styling.

**Comment by apahl** [comment]
So, it's definitely an issue with the styling on Kubuntu that can be worked around.  
When I add `style="color:black;"` to the definition of the first button, the label becomes visible:
```
...
<body>
        <button onclick="api.close()" style="color:black;">
            Close</button>
        <button onclick="api.open()">Open</button>
...
```
![bindex2](https://user-images.githubusercontent.com/9406836/34865835-7e073652-f77a-11e7-9ee0-9d53ec888924.png)

**Comment by oskca** [comment]
Or it relates to how `webview2` is initialized, like https://github.com/zserge/webview/pull/73
