### ISSUE TITLE
Javascript execution example

### ISSUE THREAD

**Issue by mratsim** [oskca/webview#4]
I probably missed something but I couldn't find a way to `eval` or `dispatch` a simple JS alert:

```Nim
import
  webview, uri

const HtmlCanvas = "data:text/html," & """<!DOCTYPE html><html><body id="body">Hello World</body></html>""".encodeUrl

let canvas = newWebView("Foobar", HtmlCanvas, 800, 600)


# canvas.dispatch(
#   proc() =
#     discard canvas.eval("alert('hello, world');")
# )

discard canvas.eval("alert('hello, world');")
canvas.run()
canvas.exit()
```

This displays "Hello+World" but there is no alert box popping up.

The end goal is to be able to generate UI code with Karax and then eval it with webview.

**Comment by mratsim** [comment]
Unfortunately yes, I'm on Mac and it doesn't seem like JS is executed with `eval`.

**Comment by oskca** [comment]
That's too bad.  I have no Mac machine to test. :hushed: 

I've update `webview.h` to the latest version, I can see some changes about `macOS` but it might not be relate to this issue, well, maybe you can have a try :smile: 

and would debug likt this helps:

To debug the web part of your app you may use `webview.Settings.Debug` flag. It
enables the Web Inspector in WebKit and works on Linux and MacOS (use popup menu
to open the web inspector). On Windows there is no easy to way to enable
debugging, but you may include Firebug in your HTML code:

```html
<script type="text/javascript" src="https://getfirebug.com/firebug-lite.js"></script>
```

**Comment by mratsim** [comment]
I digged a bit, seems like Mac is a mess.

The web inspector requires changing mac config files and registering a com.developer.app_name parameter ...

![2018-06-21_00-12-49](https://user-images.githubusercontent.com/22738317/41687415-e0c01e68-74e7-11e8-81b9-d7afdf7e4285.png)

And alert is plain not supported on MacOS webviews ...

![2018-06-21_00-12-31](https://user-images.githubusercontent.com/22738317/41687425-eb26dbb2-74e7-11e8-8f03-d118d0072fe4.png)

So closing as you can't really do anything except documenting those "corner" cases.
