### ISSUE TITLE
Directly link HTML field values to Nim vars

### ISSUE THREAD

**Issue by apahl** [oskca/webview#6]
Hi, thanks again for these great bindings!

Is it possible to create direct links between values on the HTML / JS side and Nim vars, e.g. between an input tag's `value` field and a corresponding Nim string var?
For the Go version, this seems to be possible, as described in the [module](https://github.com/zserge/webview/blob/d007fc53b107f6043c2a6a3372548dbf59dfe876/webview.go#L230) and used in the [counter](https://github.com/zserge/webview/blob/master/examples/counter-go/main.go#L30) example. I am just not sure how to do this with the Nim wrapper.

Many thanks again.  
Kind regards,

Axel

Edit 1: corrected link to counter example

**Comment by oskca** [comment]
This is possible as the `go binding` by [js code injection](https://github.com/zserge/webview/blob/d007fc53b107f6043c2a6a3372548dbf59dfe876/webview.go#L404)
